package btw.client.render;

import btw.block.tileentity.CampfireTileEntity;
import btw.block.tileentity.HamperTileEntity;
import btw.block.tileentity.OvenTileEntity;
import btw.block.tileentity.PlacedToolTileEntity;
import btw.block.tileentity.WickerBasketTileEntity;
import btw.client.render.entity.BlockLiftedByPlatformRenderer;
import btw.client.render.entity.BroadheadArrowRenderer;
import btw.client.render.entity.CanvasRenderer;
import btw.client.render.entity.DireWolfRenderer;
import btw.client.render.entity.DynamiteRenderer;
import btw.client.render.entity.InfiniteArrowRenderer;
import btw.client.render.entity.LightningBoltRenderer;
import btw.client.render.entity.MiningChargeRenderer;
import btw.client.render.entity.MovingAnchorRenderer;
import btw.client.render.entity.MovingPlatformRenderer;
import btw.client.render.entity.SoulSandRenderer;
import btw.client.render.entity.SpiderRenderer;
import btw.client.render.entity.SpiderWebRenderer;
import btw.client.render.entity.SquidRenderer;
import btw.client.render.entity.UrnRenderer;
import btw.client.render.entity.VerticalWindMillRenderer;
import btw.client.render.entity.WaterWheelRenderer;
import btw.client.render.entity.WindmillRenderer;
import btw.client.render.entity.WolfRenderer;
import btw.client.render.tileentity.BasketRenderer;
import btw.client.render.tileentity.CampfireRenderer;
import btw.client.render.tileentity.OvenRenderer;
import btw.client.render.tileentity.PlacedToolRenderer;
import btw.client.render.tileentity.WickerBasketRenderer;
import btw.entity.BroadheadArrowEntity;
import btw.entity.CanvasEntity;
import btw.entity.CorpseEyeEntity;
import btw.entity.DynamiteEntity;
import btw.entity.FallingBlockEntity;
import btw.entity.InfiniteArrowEntity;
import btw.entity.LightningBoltEntity;
import btw.entity.MiningChargeEntity;
import btw.entity.SoulSandEntity;
import btw.entity.SpiderWebEntity;
import btw.entity.UrnEntity;
import btw.entity.WitherSkullEntity;
import btw.entity.mechanical.platform.BlockLiftedByPlatformEntity;
import btw.entity.mechanical.platform.MovingAnchorEntity;
import btw.entity.mechanical.platform.MovingPlatformEntity;
import btw.entity.mechanical.source.VerticalWindMillEntity;
import btw.entity.mechanical.source.WaterWheelEntity;
import btw.entity.mechanical.source.WindMillEntity;
import btw.entity.mob.BatEntity;
import btw.entity.mob.BlazeEntity;
import btw.entity.mob.CaveSpiderEntity;
import btw.entity.mob.ChickenEntity;
import btw.entity.mob.CowEntity;
import btw.entity.mob.CreeperEntity;
import btw.entity.mob.DireWolfEntity;
import btw.entity.mob.EndermanEntity;
import btw.entity.mob.GhastEntity;
import btw.entity.mob.JungleSpiderEntity;
import btw.entity.mob.MagmaCubeEntity;
import btw.entity.mob.OcelotEntity;
import btw.entity.mob.PigEntity;
import btw.entity.mob.SheepEntity;
import btw.entity.mob.SkeletonEntity;
import btw.entity.mob.SlimeEntity;
import btw.entity.mob.SnowmanEntity;
import btw.entity.mob.SpiderEntity;
import btw.entity.mob.SquidEntity;
import btw.entity.mob.WitchEntity;
import btw.entity.mob.WitherEntity;
import btw.entity.mob.WitherEntityPersistent;
import btw.entity.mob.WolfEntity;
import btw.entity.mob.ZombieEntity;
import btw.entity.mob.ZombiePigmanEntity;
import btw.entity.mob.villager.VillagerEntity;
import btw.entity.model.ChickenModel;
import btw.entity.model.DireWolfModel;
import btw.entity.model.PigModel;
import btw.item.BTWItems;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.src.ModelCow;
import net.minecraft.src.ModelOcelot;
import net.minecraft.src.ModelSheep1;
import net.minecraft.src.ModelSheep2;
import net.minecraft.src.ModelSlime;
import net.minecraft.src.ModelWolf;
import net.minecraft.src.RenderBat;
import net.minecraft.src.RenderBlaze;
import net.minecraft.src.RenderChicken;
import net.minecraft.src.RenderCow;
import net.minecraft.src.RenderCreeper;
import net.minecraft.src.RenderEnderman;
import net.minecraft.src.RenderFallingSand;
import net.minecraft.src.RenderGhast;
import net.minecraft.src.RenderMagmaCube;
import net.minecraft.src.RenderManager;
import net.minecraft.src.RenderOcelot;
import net.minecraft.src.RenderPig;
import net.minecraft.src.RenderSheep;
import net.minecraft.src.RenderSkeleton;
import net.minecraft.src.RenderSlime;
import net.minecraft.src.RenderSnowMan;
import net.minecraft.src.RenderSnowball;
import net.minecraft.src.RenderVillager;
import net.minecraft.src.RenderWitch;
import net.minecraft.src.RenderWither;
import net.minecraft.src.RenderWitherSkull;
import net.minecraft.src.RenderZombie;
import net.minecraft.src.TileEntityRenderer;

@Environment(EnvType.CLIENT)
public class BTWRenderMapper {
   public static void initTileEntityRenderers() {
      TileEntityRenderer.instance.addSpecialRendererForClass(CampfireTileEntity.class, new CampfireRenderer());
      TileEntityRenderer.instance.addSpecialRendererForClass(OvenTileEntity.class, new OvenRenderer());
      TileEntityRenderer.instance.addSpecialRendererForClass(PlacedToolTileEntity.class, new PlacedToolRenderer());
      TileEntityRenderer.instance.addSpecialRendererForClass(WickerBasketTileEntity.class, new WickerBasketRenderer());
      TileEntityRenderer.instance.addSpecialRendererForClass(HamperTileEntity.class, new BasketRenderer());
   }

   public static void initEntityRenderers() {
      RenderManager.addEntityRenderer(WaterWheelEntity.class, new WaterWheelRenderer());
      RenderManager.addEntityRenderer(WindMillEntity.class, new WindmillRenderer());
      RenderManager.addEntityRenderer(MovingAnchorEntity.class, new MovingAnchorRenderer());
      RenderManager.addEntityRenderer(MovingPlatformEntity.class, new MovingPlatformRenderer());
      RenderManager.addEntityRenderer(BlockLiftedByPlatformEntity.class, new BlockLiftedByPlatformRenderer());
      RenderManager.addEntityRenderer(BroadheadArrowEntity.class, new BroadheadArrowRenderer());
      RenderManager.addEntityRenderer(InfiniteArrowEntity.class, new InfiniteArrowRenderer());
      RenderManager.addEntityRenderer(UrnEntity.class, new UrnRenderer());
      RenderManager.addEntityRenderer(DynamiteEntity.class, new DynamiteRenderer());
      RenderManager.addEntityRenderer(MiningChargeEntity.class, new MiningChargeRenderer());
      RenderManager.addEntityRenderer(CanvasEntity.class, new CanvasRenderer());
      RenderManager.addEntityRenderer(VerticalWindMillEntity.class, new VerticalWindMillRenderer());
      RenderManager.addEntityRenderer(SpiderWebEntity.class, new SpiderWebRenderer());
      RenderManager.addEntityRenderer(DireWolfEntity.class, new DireWolfRenderer(new DireWolfModel(), null));
      RenderManager.addEntityRenderer(SoulSandEntity.class, new SoulSandRenderer());
      RenderManager.addEntityRenderer(JungleSpiderEntity.class, new SpiderRenderer());
      RenderManager.addEntityRenderer(WitherEntityPersistent.class, new RenderWither());
      RenderManager.addEntityRenderer(CorpseEyeEntity.class, new RenderSnowball(BTWItems.corpseEye));
      RenderManager.addEntityRenderer(SpiderEntity.class, new SpiderRenderer());
      RenderManager.addEntityRenderer(CaveSpiderEntity.class, new SpiderRenderer());
      RenderManager.addEntityRenderer(PigEntity.class, new RenderPig(new PigModel(), new PigModel(0.5F), 0.7F));
      RenderManager.addEntityRenderer(SheepEntity.class, new RenderSheep(new ModelSheep2(), new ModelSheep1(), 0.7F));
      RenderManager.addEntityRenderer(CowEntity.class, new RenderCow(new ModelCow(), 0.7F));
      RenderManager.addEntityRenderer(WolfEntity.class, new WolfRenderer(new ModelWolf(), new ModelWolf(), 0.5F));
      RenderManager.addEntityRenderer(ChickenEntity.class, new RenderChicken(new ChickenModel(), 0.3F));
      RenderManager.addEntityRenderer(OcelotEntity.class, new RenderOcelot(new ModelOcelot(), 0.4F));
      RenderManager.addEntityRenderer(CreeperEntity.class, new RenderCreeper());
      RenderManager.addEntityRenderer(EndermanEntity.class, new RenderEnderman());
      RenderManager.addEntityRenderer(SnowmanEntity.class, new RenderSnowMan());
      RenderManager.addEntityRenderer(SkeletonEntity.class, new RenderSkeleton());
      RenderManager.addEntityRenderer(WitchEntity.class, new RenderWitch());
      RenderManager.addEntityRenderer(BlazeEntity.class, new RenderBlaze());
      RenderManager.addEntityRenderer(ZombieEntity.class, new RenderZombie());
      RenderManager.addEntityRenderer(SlimeEntity.class, new RenderSlime(new ModelSlime(16), new ModelSlime(0), 0.25F));
      RenderManager.addEntityRenderer(MagmaCubeEntity.class, new RenderMagmaCube());
      RenderManager.addEntityRenderer(GhastEntity.class, new RenderGhast());
      RenderManager.addEntityRenderer(SquidEntity.class, new SquidRenderer());
      RenderManager.addEntityRenderer(VillagerEntity.class, new RenderVillager());
      RenderManager.addEntityRenderer(BatEntity.class, new RenderBat());
      RenderManager.addEntityRenderer(WitherEntity.class, new RenderWither());
      RenderManager.addEntityRenderer(WitherSkullEntity.class, new RenderWitherSkull());
      RenderManager.addEntityRenderer(FallingBlockEntity.class, new RenderFallingSand());
      RenderManager.addEntityRenderer(LightningBoltEntity.class, new LightningBoltRenderer());
      RenderManager.addEntityRenderer(ZombiePigmanEntity.class, new RenderZombie());
   }
}
